export const POST_ADD = 'POST_ADD';
export const POST_TOGGLE_LIKE = 'POST_TOGGLE_LIKE';
export const POST_TOGGLE_REPOST = 'POST_TOGGLE_REPOST';
export const NEW_POST_IDS_RESET = 'NEW_POST_IDS_RESET';

export const USER_SET_NAME = 'USER_SET_NAME';
export const USER_SET_HANDLE = 'USER_SET_HANDLE';
